import requests
from bs4 import BeautifulSoup
import smtplib
import time

URL = 'https://www.amazon.in/Call-Duty-Modern-Warfare-PS4/dp/B07SPWYF9L/ref=sr_1_1?crid=3RMVAHXZNXTPN&keywords=call+of+duty+modern+warfare+ps4&qid=1573999412&sprefix=call+of+duty%2Caps%2C274&sr=8-1'

headers = {"User-Agent": '#search my user agent on your browser and paste it here'}

def check_price():
    page = requests.get(URL, headers = headers)

    soup = BeautifulSoup(page.content, 'html.parser')

    title = soup.find(id="productTitle").get_text()
    price = soup.find(id="priceblock_ourprice").get_text()
    converted_price =float(price[3] + price[5:8])

    if(converted_price > 2000):
        send_mail()

    print(converted_price)
    print(title.strip())
    #before this step unable 2 step verification and then go to google app passwords and then generate a new password for your mail fr security reasons

def send_mail():
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.ehlo()

    server.login('#email used to send mail', '#password generated by google app password')

    subject = 'Price fell down!'
    body = 'Check the amazon link https://www.amazon.in/Call-Duty-Modern-Warfare-PS4/dp/B07SPWYF9L/ref=sr_1_1?crid=3RMVAHXZNXTPN&keywords=call+of+duty+modern+warfare+ps4&qid=1573999412&sprefix=call+of+duty%2Caps%2C274&sr=8-1'
    
    msg = f"Subject: {subject}\n\n{body}"

    server.sendmail(
        '#email from',
        '#email to',
        msg
    )
    print('EMAIL HAS BEEN SENT!!')

    server.quit()

while(True):
    check_price()
    time.sleep(60 * 60)
